### ISSUE TITLE
Faulty/missing test for #all_students_in_grade_X

### ISSUE THREAD

**Issue by ivalentine** [learn-co-students/orm-mapping-db-to-ruby-object-lab-v-000#142]
The test for the `#all_students_in_grade_X` method only exists on the `master` branch — not on `solution`.

Additionally, the test calls the method without an argument, which makes it impossible to specify a given grade.

Credit to @PeteAJ for reporting.

@aturkewi @antoinfive

**Comment by aturkewi** [comment]
Closing issue, there are already some issue pointing this out on the canonical version of the lab.
